### ISSUE TITLE
Benefits of bag8 - README

### ISSUE THREAD

**Issue by xcambar** [novafloss/bag8#36]
As bag8 is an open source project, it is important that people have a clear idea of the benefits.

* What is bag8?
* Why should people use it?
* How is it different from other projects?

The project should be obvious within the first 5 sentences of the README, even and mostly to someone without prior knowledge of the project.

Good luck and have fun, it's a very insightful yet tough thing to do!

**Comment by xcambar** [comment]
ping

**Comment by bersace** [comment]
> http://dusty.gc.com/

:)

**Comment by xcambar** [comment]
Not sure I understand. Are you suggesting that we move to Dusty?

**Comment by bersace** [comment]
Non, c'est le même but, mais sous Linux et moins mature au premier abord.
